### ISSUE TITLE
Access Token on first build

### ISSUE THREAD

**Issue by Mstuart712** [schnick3rs/wang-charz#61]
Hello everyone I am new to this project and tried to start it up for the first time. On build I get an error about an expected parameter accessToken. I am not familiar with contentful and nuxt. Is there another part of setup I need to do outside of "npm run dev"

![image](https://user-images.githubusercontent.com/4827156/103160202-2addb380-478f-11eb-8402-a3448384f091.png)

`
 ERROR  ServerMiddleware Error: Expected parameter accessToken                                                15:19:46

  TypeError: Expected parameter accessToken
  at Module.createClient (node_modules\contentful\dist\contentful.node.js:5745:11)
  at Object.<anonymous> (api\routes\homebrews.js:18:27)
  at Generator.next (<anonymous>)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)`

**Comment by brother-lucius** [comment]
Oh hi, I just noticed. Sorry, I was not ignoring it, I just did not check the issue section often :D

So, the project is not intended to run without issues outside my usual setup. I need to check. Some data is fetched from external points, thus the access tokens are not part of the public repository.
